// Auto-generated ESM entry
import "../../src/Defines.debug";
import * as $m0 from "../../src/egret/display/BitmapFillMode";
egret.BitmapFillMode = $m0.BitmapFillMode;
import * as $m1 from "../../src/egret/display/OrientationMode";
egret.OrientationMode = $m1.OrientationMode;
import * as $m2 from "../../src/egret/events/EventPhase";
egret.EventPhase = $m2.EventPhase;
import * as $m3 from "../../src/egret/i18n/tr";
egret.$locale_strings = $m3.$locale_strings;
egret.$language = $m3.$language;
egret.set = $m3.set;
egret.tr = $m3.tr;
import * as $m4 from "../../src/egret/localStorage/localStorage";
egret.getItem = $m4.getItem;
egret.setItem = $m4.setItem;
egret.removeItem = $m4.removeItem;
egret.clear = $m4.clear;
import * as $m5 from "../../src/egret/player/nodes/RenderNode";
egret.RenderNode = $m5.RenderNode;
egret.RenderNodeType = $m5.RenderNodeType;
import * as $m6 from "../../src/egret/player/paths/Path2D";
egret.Path2D = $m6.Path2D;
import * as $m7 from "../../src/egret/player/RenderBuffer";
egret.customHitTestBuffer = $m7.customHitTestBuffer;
egret.canvasHitTestBuffer = $m7.canvasHitTestBuffer;
egret.setCustomHitTestBuffer = $m7.setCustomHitTestBuffer;
egret.setCanvasHitTestBuffer = $m7.setCanvasHitTestBuffer;
egret.RenderBuffer = $m7.RenderBuffer;
egret.CanvasRenderBuffer = $m7.CanvasRenderBuffer;
import * as $m8 from "../../src/egret/player/StageScaleMode";
egret.StageScaleMode = $m8.StageScaleMode;
import * as $m9 from "../../src/egret/system/Capabilities";
egret.WEB = $m9.WEB;
egret.NATIVE = $m9.NATIVE;
egret.RUNTIME2 = $m9.RUNTIME2;
egret.MYGAME = $m9.MYGAME;
egret.WXGAME = $m9.WXGAME;
egret.BAIDUGAME = $m9.BAIDUGAME;
egret.QGAME = $m9.QGAME;
egret.OPPOGAME = $m9.OPPOGAME;
egret.QQGAME = $m9.QQGAME;
egret.VIVOGAME = $m9.VIVOGAME;
egret.QHGAME = $m9.QHGAME;
egret.TTGAME = $m9.TTGAME;
egret.FASTGAME = $m9.FASTGAME;
egret.TBCREATIVEAPP = $m9.TBCREATIVEAPP;
egret.Capabilities = $m9.Capabilities;
import * as $m10 from "../../src/egret/system/Console";
egret.assert = $m10.assert;
egret.setAssert = $m10.setAssert;
egret.warn = $m10.warn;
egret.error = $m10.error;
egret.log = $m10.log;
egret.setWarn = $m10.setWarn;
egret.setError = $m10.setError;
egret.setLog = $m10.setLog;
import * as $m11 from "../../src/egret/text/Font";
egret.fontResourceCache = $m11.fontResourceCache;
egret.setRegisterFontMapping = $m11.setRegisterFontMapping;
egret.registerFontMapping = $m11.registerFontMapping;
import * as $m12 from "../../src/egret/text/HorizontalAlign";
egret.HorizontalAlign = $m12.HorizontalAlign;
import * as $m13 from "../../src/egret/text/TextFieldInputType";
egret.TextFieldInputType = $m13.TextFieldInputType;
import * as $m14 from "../../src/egret/text/TextFieldType";
egret.TextFieldType = $m14.TextFieldType;
import * as $m15 from "../../src/egret/text/TextMeasurer";
egret.measureText = $m15.measureText;
import * as $m16 from "../../src/egret/utils/Base64Util";
egret.Base64Util = $m16.Base64Util;
import * as $m17 from "../../src/egret/utils/ByteArray";
egret.Endian = $m17.Endian;
egret.ByteArray = $m17.ByteArray;
import * as $m18 from "../../src/egret/utils/callLater";
egret.$callLaterFunctionList = $m18.$callLaterFunctionList;
egret.$callLaterThisList = $m18.$callLaterThisList;
egret.$callLaterArgsList = $m18.$callLaterArgsList;
egret.callLater = $m18.callLater;
egret.callAsyncState = $m18.callAsyncState;
egret.$callAsync = $m18.$callAsync;
import * as $m19 from "../../src/egret/utils/DataStructure";
egret.createMap = $m19.createMap;
import * as $m20 from "../../src/egret/utils/extends";
egret.superSetter = $m20.superSetter;
egret.superGetter = $m20.superGetter;
import * as $m21 from "../../src/egret/utils/getDefinitionByName";
egret.getDefinitionByName = $m21.getDefinitionByName;
import * as $m22 from "../../src/egret/utils/getOption";
egret.getOption = $m22.getOption;
import * as $m23 from "../../src/egret/utils/getQualifiedClassName";
egret.getQualifiedClassName = $m23.getQualifiedClassName;
import * as $m24 from "../../src/egret/utils/getQualifiedSuperclassName";
egret.getQualifiedSuperclassName = $m24.getQualifiedSuperclassName;
import * as $m25 from "../../src/egret/utils/HashObject";
egret.$hashCount = $m25.$hashCount;
egret.HashObject = $m25.HashObject;
import * as $m26 from "../../src/egret/utils/Logger";
egret.Logger = $m26.Logger;
import * as $m27 from "../../src/egret/utils/NumberUtils";
egret.NumberUtils = $m27.NumberUtils;
import * as $m28 from "../../src/egret/utils/toColorString";
egret.toColorString = $m28.toColorString;
import * as $m29 from "../../src/egret/web/rendering/webgl/shaders/EgretShaderLib";
egret.EgretShaderLib = $m29.EgretShaderLib;
import * as $m30 from "../../src/egret/web/rendering/webgl/WebGLUtils";
egret.WebGLUtils = $m30.WebGLUtils;
import * as $m31 from "../../src/egret/web/WebGetOption";
import * as $m32 from "../../src/egret/web/WebHideHandler";
egret.WebLifeCycleHandler = $m32.WebLifeCycleHandler;
import * as $m33 from "../../src/egret/web/WebXML";
egret.XMLNode = $m33.XMLNode;
egret.XML = $m33.XML;
egret.XMLText = $m33.XMLText;
import * as $m34 from "../../src/egret/player/nodes/TextNode";
egret.TextNode = $m34.TextNode;
import * as $m35 from "../../src/egret/player/paths/FillPath";
egret.FillPath = $m35.FillPath;
import * as $m36 from "../../src/egret/player/paths/StrokePath";
egret.StrokePath = $m36.StrokePath;
import * as $m37 from "../../src/egret/web/WebCapability";
egret.WebCapability = $m37.WebCapability;
import * as $m38 from "../../src/egret/geom/Point";
egret.$TempPoint = $m38.$TempPoint;
egret.Point = $m38.Point;
import * as $m39 from "../../src/egret/player/ScreenAdapter";
egret.screenAdapter = $m39.screenAdapter;
egret.setScreenAdapter = $m39.setScreenAdapter;
egret.DefaultScreenAdapter = $m39.DefaultScreenAdapter;
import * as $m40 from "../../src/egret/web/rendering/webgl/TextAtlasStrategy";
egret.TextBlock = $m40.TextBlock;
egret.Line = $m40.Line;
egret.Page = $m40.Page;
egret.Book = $m40.Book;
import * as $m41 from "../../src/egret/web/rendering/webgl/WebGLRenderTarget";
egret.WebGLRenderTarget = $m41.WebGLRenderTarget;
import * as $m42 from "../../src/egret/geom/Rectangle";
egret.$TempRectangle = $m42.$TempRectangle;
egret.Rectangle = $m42.Rectangle;
import * as $m43 from "../../src/egret/geom/Matrix";
egret.$TempMatrix = $m43.$TempMatrix;
egret.Matrix = $m43.Matrix;
import * as $m44 from "../../src/egret/player/nodes/GroupNode";
egret.GroupNode = $m44.GroupNode;
import * as $m45 from "../../src/egret/player/paths/GradientFillPath";
egret.GradientFillPath = $m45.GradientFillPath;
import * as $m46 from "../../src/egret/player/nodes/GraphicsNode";
egret.GraphicsNode = $m46.GraphicsNode;
import * as $m47 from "../../src/egret/3d/EgretPro";
egret.egret2dDriveMode = $m47.egret2dDriveMode;
egret.mainCanvas = $m47.mainCanvas;
egret.createTextureFrom3dScene = $m47.createTextureFrom3dScene;
egret.createTextureForCameras = $m47.createTextureForCameras;
egret.execute = $m47.execute;
egret.register = $m47.register;
egret.addEventListener = $m47.addEventListener;
egret.removeEventListener = $m47.removeEventListener;
egret.dispatch = $m47.dispatch;
import * as $m48 from "../../src/egret/display/Bitmap";
egret.Bitmap = $m48.Bitmap;
import * as $m49 from "../../src/egret/display/BitmapData";
egret.etc_alpha_mask = $m49.etc_alpha_mask;
egret.engine_default_empty_texture = $m49.engine_default_empty_texture;
egret.is_compressed_texture = $m49.is_compressed_texture;
egret.glContext = $m49.glContext;
egret.UNPACK_PREMULTIPLY_ALPHA_WEBGL = $m49.UNPACK_PREMULTIPLY_ALPHA_WEBGL;
egret.CompressedTextureData = $m49.CompressedTextureData;
egret.BitmapData = $m49.BitmapData;
import * as $m50 from "../../src/egret/display/BlendMode";
egret.blendModeToNumber = $m50.blendModeToNumber;
egret.numberToBlendMode = $m50.numberToBlendMode;
egret.BlendMode = $m50.BlendMode;
import * as $m51 from "../../src/egret/display/CapsStyle";
egret.CapsStyle = $m51.CapsStyle;
import * as $m52 from "../../src/egret/display/DisplayObject";
egret.DisplayObject = $m52.DisplayObject;
import * as $m53 from "../../src/egret/display/DisplayObjectContainer";
egret.DisplayObjectContainer = $m53.DisplayObjectContainer;
import * as $m54 from "../../src/egret/display/GradientType";
egret.GradientType = $m54.GradientType;
import * as $m55 from "../../src/egret/display/Graphics";
egret.Graphics = $m55.Graphics;
import * as $m56 from "../../src/egret/display/JointStyle";
egret.JointStyle = $m56.JointStyle;
import * as $m57 from "../../src/egret/display/KTXContainer";
egret.KTXContainer = $m57.KTXContainer;
import * as $m58 from "../../src/egret/display/Mesh";
egret.Mesh = $m58.Mesh;
import * as $m59 from "../../src/egret/display/RenderTexture";
egret.RenderTexture = $m59.RenderTexture;
import * as $m60 from "../../src/egret/display/Shape";
egret.Shape = $m60.Shape;
import * as $m61 from "../../src/egret/display/Sprite";
egret.Sprite = $m61.Sprite;
import * as $m62 from "../../src/egret/display/SpriteSheet";
egret.SpriteSheet = $m62.SpriteSheet;
import * as $m63 from "../../src/egret/display/Stage";
egret.Stage = $m63.Stage;
import * as $m64 from "../../src/egret/display/Texture";
egret.$TextureScaleFactor = $m64.$TextureScaleFactor;
egret.Texture = $m64.Texture;
import * as $m65 from "../../src/egret/events/Event";
egret.Event = $m65.Event;
import * as $m66 from "../../src/egret/events/EventDispatcher";
egret.EventDispatcher = $m66.EventDispatcher;
import * as $m67 from "../../src/egret/events/FocusEvent";
egret.FocusEvent = $m67.FocusEvent;
import * as $m68 from "../../src/egret/events/GeolocationEvent";
egret.GeolocationEvent = $m68.GeolocationEvent;
import * as $m69 from "../../src/egret/events/HTTPStatusEvent";
egret.HTTPStatusEvent = $m69.HTTPStatusEvent;
import * as $m70 from "../../src/egret/events/IOErrorEvent";
egret.IOErrorEvent = $m70.IOErrorEvent;
import * as $m71 from "../../src/egret/events/MotionEvent";
egret.MotionEvent = $m71.MotionEvent;
import * as $m72 from "../../src/egret/events/OrientationEvent";
egret.OrientationEvent = $m72.OrientationEvent;
import * as $m73 from "../../src/egret/events/ProgressEvent";
egret.ProgressEvent = $m73.ProgressEvent;
import * as $m74 from "../../src/egret/events/StageOrientationEvent";
egret.StageOrientationEvent = $m74.StageOrientationEvent;
import * as $m75 from "../../src/egret/events/TextEvent";
egret.TextEvent = $m75.TextEvent;
import * as $m76 from "../../src/egret/events/TimerEvent";
egret.TimerEvent = $m76.TimerEvent;
import * as $m77 from "../../src/egret/events/TouchEvent";
egret.TouchEvent = $m77.TouchEvent;
import * as $m78 from "../../src/egret/filters/BlurFilter";
egret.BlurFilter = $m78.BlurFilter;
import * as $m79 from "../../src/egret/filters/ColorMatrixFilter";
egret.ColorMatrixFilter = $m79.ColorMatrixFilter;
import * as $m80 from "../../src/egret/filters/CustomFilter";
egret.CustomFilter = $m80.CustomFilter;
import * as $m81 from "../../src/egret/filters/DropShadowFilter";
egret.DropShadowFilter = $m81.DropShadowFilter;
import * as $m82 from "../../src/egret/filters/Filter";
egret.Filter = $m82.Filter;
import * as $m83 from "../../src/egret/filters/GlowFilter";
egret.GlowFilter = $m83.GlowFilter;
import * as $m84 from "../../src/egret/media/Sound";
egret.usingChannel = $m84.usingChannel;
egret.$pushSoundChannel = $m84.$pushSoundChannel;
egret.$popSoundChannel = $m84.$popSoundChannel;
egret.setSound = $m84.setSound;
egret.Sound = $m84.Sound;
import * as $m85 from "../../src/egret/media/Video";
egret.Video = $m85.Video;
egret.setVideo = $m85.setVideo;
import * as $m86 from "../../src/egret/media/web/HtmlSound";
egret.HtmlSound = $m86.HtmlSound;
import * as $m87 from "../../src/egret/media/web/HtmlSoundChannel";
egret.HtmlSoundChannel = $m87.HtmlSoundChannel;
import * as $m88 from "../../src/egret/media/web/WebAudioSound";
egret.WebAudioDecode = $m88.WebAudioDecode;
egret.WebAudioSound = $m88.WebAudioSound;
import * as $m89 from "../../src/egret/media/web/WebAudioSoundChannel";
egret.WebAudioSoundChannel = $m89.WebAudioSoundChannel;
import * as $m90 from "../../src/egret/media/web/WebVideo";
egret.WebVideo = $m90.WebVideo;
import * as $m91 from "../../src/egret/net/HttpMethod";
egret.GET = $m91.GET;
egret.POST = $m91.POST;
import * as $m92 from "../../src/egret/net/HttpRequest";
egret.setHttpRequest = $m92.setHttpRequest;
egret.HttpRequest = $m92.HttpRequest;
import * as $m93 from "../../src/egret/net/HttpResponseType";
egret.HttpResponseType = $m93.HttpResponseType;
import * as $m94 from "../../src/egret/net/ImageLoader";
egret.setImageLoader = $m94.setImageLoader;
egret.ImageLoader = $m94.ImageLoader;
import * as $m95 from "../../src/egret/net/web/WebHttpRequest";
egret.WebHttpRequest = $m95.WebHttpRequest;
import * as $m96 from "../../src/egret/net/web/WebImageLoader";
egret.WebImageLoader = $m96.WebImageLoader;
import * as $m97 from "../../src/egret/player/DisplayList";
egret.DisplayList = $m97.DisplayList;
import * as $m98 from "../../src/egret/player/FPSDisplay";
egret.setFPSDisplay = $m98.setFPSDisplay;
egret.FPSDisplay = $m98.FPSDisplay;
import * as $m99 from "../../src/egret/player/nodes/BitmapNode";
egret.BitmapNode = $m99.BitmapNode;
import * as $m100 from "../../src/egret/player/nodes/MeshNode";
egret.MeshNode = $m100.MeshNode;
import * as $m101 from "../../src/egret/player/nodes/NormalBitmapNode";
egret.NormalBitmapNode = $m101.NormalBitmapNode;
import * as $m102 from "../../src/egret/player/Player";
egret.$TempStage = $m102.$TempStage;
egret.$logToFPS = $m102.$logToFPS;
egret.$warnToFPS = $m102.$warnToFPS;
egret.$errorToFPS = $m102.$errorToFPS;
egret.setRenderMode = $m102.setRenderMode;
egret.setWebGLRenderContext = $m102.setWebGLRenderContext;
egret.WebGLRenderContext = $m102.WebGLRenderContext;
egret.nativeRender = $m102.nativeRender;
egret.Player = $m102.Player;
import * as $m103 from "../../src/egret/player/rendering/CanvasRenderer";
egret.getFontString = $m103.getFontString;
egret.getRGBAString = $m103.getRGBAString;
egret.CanvasRenderer = $m103.CanvasRenderer;
import * as $m104 from "../../src/egret/player/SystemRenderer";
egret.systemRenderer = $m104.systemRenderer;
egret.canvasRenderer = $m104.canvasRenderer;
egret.setSystemRenderer = $m104.setSystemRenderer;
egret.setCanvasRenderer = $m104.setCanvasRenderer;
egret.createCanvas = $m104.createCanvas;
egret.resizeContext = $m104.resizeContext;
egret.getContextWebGL = $m104.getContextWebGL;
egret.getContext2d = $m104.getContext2d;
egret.createTexture = $m104.createTexture;
egret._createTexture = $m104._createTexture;
egret.drawTextureElements = $m104.drawTextureElements;
egret.measureTextWith = $m104.measureTextWith;
egret.createCanvasRenderBufferSurface = $m104.createCanvasRenderBufferSurface;
egret.resizeCanvasRenderBuffer = $m104.resizeCanvasRenderBuffer;
import * as $m105 from "../../src/egret/player/SystemTicker";
egret.$START_TIME = $m105.$START_TIME;
egret.$invalidateRenderFlag = $m105.$invalidateRenderFlag;
egret.invalidateRenderFlag = $m105.invalidateRenderFlag;
egret.$requestRenderingFlag = $m105.$requestRenderingFlag;
egret.stage = $m105.stage;
egret.contexts = $m105.contexts;
egret.onResume = $m105.onResume;
egret.onPause = $m105.onPause;
egret.addLifecycleListener = $m105.addLifecycleListener;
egret.ticker = $m105.ticker;
egret.SystemTicker = $m105.SystemTicker;
egret.LifecycleContext = $m105.LifecycleContext;
import * as $m106 from "../../src/egret/player/TouchHandler";
egret.TouchHandler = $m106.TouchHandler;
import * as $m107 from "../../src/egret/sensor/DeviceOrientation";
egret.DeviceOrientation = $m107.DeviceOrientation;
egret.setDeviceOrientation = $m107.setDeviceOrientation;
import * as $m108 from "../../src/egret/sensor/Geolocation";
egret.setGeolocation = $m108.setGeolocation;
egret.Geolocation = $m108.Geolocation;
import * as $m109 from "../../src/egret/sensor/Motion";
egret.setMotion = $m109.setMotion;
egret.Motion = $m109.Motion;
import * as $m110 from "../../src/egret/sensor/web/WebDeviceOrientation";
egret.WebDeviceOrientation = $m110.WebDeviceOrientation;
import * as $m111 from "../../src/egret/sensor/web/WebGeolocation";
egret.WebGeolocation = $m111.WebGeolocation;
import * as $m112 from "../../src/egret/sensor/web/WebMotion";
egret.WebMotion = $m112.WebMotion;
import * as $m113 from "../../src/egret/system/Implementation";
egret.registerImplementation = $m113.registerImplementation;
egret.getImplementation = $m113.getImplementation;
import * as $m114 from "../../src/egret/text/BitmapFont";
egret.BitmapFont = $m114.BitmapFont;
import * as $m115 from "../../src/egret/text/BitmapText";
egret.BitmapText = $m115.BitmapText;
import * as $m116 from "../../src/egret/text/HtmlTextParser";
egret.HtmlTextParser = $m116.HtmlTextParser;
import * as $m117 from "../../src/egret/text/InputController";
egret.InputController = $m117.InputController;
import * as $m118 from "../../src/egret/text/StageText";
egret.StageText = $m118.StageText;
egret.setStageText = $m118.setStageText;
import * as $m119 from "../../src/egret/text/TextField";
egret.addLanguageWordWrapRegex = $m119.addLanguageWordWrapRegex;
egret.getAllSupportLanguageWordWrap = $m119.getAllSupportLanguageWordWrap;
egret.getUsingWordWrap = $m119.getUsingWordWrap;
egret.cancelLanguageWordWrapRegex = $m119.cancelLanguageWordWrapRegex;
egret.TextField = $m119.TextField;
egret.TextKeys = $m119.TextKeys;
import * as $m120 from "../../src/egret/text/TextFieldUtils";
egret.TextFieldUtils = $m120.TextFieldUtils;
import * as $m121 from "../../src/egret/text/VerticalAlign";
egret.VerticalAlign = $m121.VerticalAlign;
import * as $m122 from "../../src/egret/text/web/HTML5StageText";
egret.$getTextAdapter = $m122.$getTextAdapter;
egret.$cacheTextAdapter = $m122.$cacheTextAdapter;
egret.HTML5StageText = $m122.HTML5StageText;
egret.HTMLInput = $m122.HTMLInput;
import * as $m123 from "../../src/egret/utils/getTimer";
egret.getTimer = $m123.getTimer;
import * as $m124 from "../../src/egret/utils/hasDefinition";
egret.hasDefinition = $m124.hasDefinition;
import * as $m125 from "../../src/egret/utils/is";
egret.is = $m125.is;
import * as $m126 from "../../src/egret/utils/registerClass";
egret.registerClass = $m126.registerClass;
import * as $m127 from "../../src/egret/utils/startTick";
egret.startTick = $m127.startTick;
import * as $m128 from "../../src/egret/utils/stopTick";
egret.stopTick = $m128.stopTick;
import * as $m129 from "../../src/egret/utils/Timer";
egret.Timer = $m129.Timer;
import * as $m130 from "../../src/egret/utils/XML";
import * as $m131 from "../../src/egret/web/Html5Capatibility";
egret.getPrefixStyleName = $m131.getPrefixStyleName;
egret.getPrefix = $m131.getPrefix;
egret.AudioType = $m131.AudioType;
egret.Html5Capatibility = $m131.Html5Capatibility;
import * as $m132 from "../../src/egret/web/rendering/CanvasRenderBuffer";
import * as $m133 from "../../src/egret/web/rendering/webgl/EgretWebGLAttribute";
egret.EgretWebGLAttribute = $m133.EgretWebGLAttribute;
import * as $m134 from "../../src/egret/web/rendering/webgl/EgretWebGLProgram";
egret.EgretWebGLProgram = $m134.EgretWebGLProgram;
import * as $m135 from "../../src/egret/web/rendering/webgl/EgretWebGLUniform";
egret.EgretWebGLUniform = $m135.EgretWebGLUniform;
import * as $m136 from "../../src/egret/web/rendering/webgl/TextAtlasRender";
egret.textAtlasRenderEnable = $m136.textAtlasRenderEnable;
egret.__textAtlasRender__ = $m136.__textAtlasRender__;
egret.property_drawLabel = $m136.property_drawLabel;
egret.DrawLabel = $m136.DrawLabel;
egret.TextAtlasRender = $m136.TextAtlasRender;
import * as $m137 from "../../src/egret/web/rendering/webgl/WebGLDrawCmdManager";
egret.WebGLDrawCmdManager = $m137.WebGLDrawCmdManager;
import * as $m138 from "../../src/egret/web/rendering/webgl/WebGLRenderBuffer";
egret.renderBufferPool = $m138.renderBufferPool;
egret.WebGLRenderBuffer = $m138.WebGLRenderBuffer;
import * as $m139 from "../../src/egret/web/rendering/webgl/WebGLRenderContext";
import * as $m140 from "../../src/egret/web/rendering/webgl/WebGLRenderer";
egret.WebGLRenderer = $m140.WebGLRenderer;
import * as $m141 from "../../src/egret/web/rendering/webgl/WebGLVertexArrayObject";
egret.isIOS14Device = $m141.isIOS14Device;
egret.setIsIOS14Device = $m141.setIsIOS14Device;
egret.WebGLVertexArrayObject = $m141.WebGLVertexArrayObject;
import * as $m142 from "../../src/egret/web/WebFps";
egret.WebFps = $m142.WebFps;
import * as $m143 from "../../src/egret/web/WebPlayer";
egret.WebPlayer = $m143.WebPlayer;
import * as $m144 from "../../src/egret/web/WebSysImpl";
import * as $m145 from "../../src/egret/web/WebTouchHandler";
egret.WebTouchHandler = $m145.WebTouchHandler;
import * as $m146 from "../../src/extension/eui/core/Direction";
eui.Direction = $m146.Direction;
import * as $m147 from "../../src/extension/eui/core/ScrollPolicy";
eui.ScrollPolicy = $m147.ScrollPolicy;
import * as $m148 from "../../src/extension/eui/events/CollectionEventKind";
eui.CollectionEventKind = $m148.CollectionEventKind;
import * as $m149 from "../../src/extension/eui/layouts/ColumnAlign";
eui.ColumnAlign = $m149.ColumnAlign;
import * as $m150 from "../../src/extension/eui/layouts/JustifyAlign";
eui.JustifyAlign = $m150.JustifyAlign;
import * as $m151 from "../../src/extension/eui/layouts/RowAlign";
eui.RowAlign = $m151.RowAlign;
import * as $m152 from "../../src/extension/eui/layouts/TileOrientation";
eui.TileOrientation = $m152.TileOrientation;
import * as $m153 from "../../src/extension/eui/utils/registerBindable";
eui.registerBindable = $m153.registerBindable;
import * as $m154 from "../../src/extension/eui/exml/EXMLConfig";
eui.NS_S = $m154.NS_S;
eui.NS_W = $m154.NS_W;
eui.EXMLConfig = $m154.EXMLConfig;
import * as $m155 from "../../src/extension/eui/binding/Binding";
eui.Binding = $m155.Binding;
import * as $m156 from "../../src/extension/eui/binding/Watcher";
eui.Watcher = $m156.Watcher;
import * as $m157 from "../../src/extension/eui/collections/ArrayCollection";
eui.ArrayCollection = $m157.ArrayCollection;
import * as $m158 from "../../src/extension/eui/components/BitmapLabel";
eui.BitmapLabel = $m158.BitmapLabel;
import * as $m159 from "../../src/extension/eui/components/Button";
eui.Button = $m159.Button;
import * as $m160 from "../../src/extension/eui/components/CheckBox";
eui.CheckBox = $m160.CheckBox;
import * as $m161 from "../../src/extension/eui/components/Component";
eui.Component = $m161.Component;
eui.ComponentKeys = $m161.ComponentKeys;
import * as $m162 from "../../src/extension/eui/components/DataGroup";
eui.DataGroup = $m162.DataGroup;
import * as $m163 from "../../src/extension/eui/components/EditableText";
eui.EditableText = $m163.EditableText;
eui.EditableTextKeys = $m163.EditableTextKeys;
import * as $m164 from "../../src/extension/eui/components/Group";
eui.Group = $m164.Group;
import * as $m165 from "../../src/extension/eui/components/HScrollBar";
eui.HScrollBar = $m165.HScrollBar;
import * as $m166 from "../../src/extension/eui/components/HSlider";
eui.HSlider = $m166.HSlider;
import * as $m167 from "../../src/extension/eui/components/Image";
eui.Image = $m167.Image;
import * as $m168 from "../../src/extension/eui/components/ItemRenderer";
eui.ItemRenderer = $m168.ItemRenderer;
import * as $m169 from "../../src/extension/eui/components/Label";
eui.Label = $m169.Label;
import * as $m170 from "../../src/extension/eui/components/List";
eui.List = $m170.List;
import * as $m171 from "../../src/extension/eui/components/Panel";
eui.Panel = $m171.Panel;
import * as $m172 from "../../src/extension/eui/components/ProgressBar";
eui.ProgressBar = $m172.ProgressBar;
import * as $m173 from "../../src/extension/eui/components/RadioButton";
eui.RadioButton = $m173.RadioButton;
import * as $m174 from "../../src/extension/eui/components/RadioButtonGroup";
eui.RadioButtonGroup = $m174.RadioButtonGroup;
import * as $m175 from "../../src/extension/eui/components/Rect";
eui.Rect = $m175.Rect;
import * as $m176 from "../../src/extension/eui/components/Scroller";
eui.Scroller = $m176.Scroller;
import * as $m177 from "../../src/extension/eui/components/Skin";
eui.Skin = $m177.Skin;
import * as $m178 from "../../src/extension/eui/components/supportClasses/Animation";
eui.Animation = $m178.Animation;
import * as $m179 from "../../src/extension/eui/components/supportClasses/DefaultAssetAdapter";
eui.DefaultAssetAdapter = $m179.DefaultAssetAdapter;
import * as $m180 from "../../src/extension/eui/components/supportClasses/DefaultThemeAdapter";
eui.DefaultThemeAdapter = $m180.DefaultThemeAdapter;
import * as $m181 from "../../src/extension/eui/components/supportClasses/ListBase";
eui.ListBase = $m181.ListBase;
import * as $m182 from "../../src/extension/eui/components/supportClasses/Range";
eui.Range = $m182.Range;
eui.RangeKeys = $m182.RangeKeys;
import * as $m183 from "../../src/extension/eui/components/supportClasses/ScrollBarBase";
eui.ScrollBarBase = $m183.ScrollBarBase;
import * as $m184 from "../../src/extension/eui/components/supportClasses/SliderBase";
eui.SliderBase = $m184.SliderBase;
import * as $m185 from "../../src/extension/eui/components/supportClasses/TouchScroll";
eui.TouchScroll = $m185.TouchScroll;
import * as $m186 from "../../src/extension/eui/components/TabBar";
eui.TabBar = $m186.TabBar;
import * as $m187 from "../../src/extension/eui/components/TextInput";
eui.TextInput = $m187.TextInput;
eui.TextInputKeys = $m187.TextInputKeys;
import * as $m188 from "../../src/extension/eui/components/ToggleButton";
eui.ToggleButton = $m188.ToggleButton;
import * as $m189 from "../../src/extension/eui/components/ToggleSwitch";
eui.ToggleSwitch = $m189.ToggleSwitch;
import * as $m190 from "../../src/extension/eui/components/UILayer";
eui.UILayer = $m190.UILayer;
import * as $m191 from "../../src/extension/eui/components/ViewStack";
eui.ViewStack = $m191.ViewStack;
import * as $m192 from "../../src/extension/eui/components/VScrollBar";
eui.VScrollBar = $m192.VScrollBar;
import * as $m193 from "../../src/extension/eui/components/VSlider";
eui.VSlider = $m193.VSlider;
import * as $m194 from "../../src/extension/eui/core/Theme";
eui.Theme = $m194.Theme;
import * as $m195 from "../../src/extension/eui/core/UIComponent";
eui.getAssets = $m195.getAssets;
eui.getTheme = $m195.getTheme;
eui.mixin = $m195.mixin;
eui.implementUIComponent = $m195.implementUIComponent;
eui.UIComponentImpl = $m195.UIComponentImpl;
eui.UIKeys = $m195.UIKeys;
import * as $m196 from "../../src/extension/eui/core/Validator";
eui.Validator = $m196.Validator;
import * as $m197 from "../../src/extension/eui/events/CollectionEvent";
eui.CollectionEvent = $m197.CollectionEvent;
import * as $m198 from "../../src/extension/eui/events/ItemTapEvent";
eui.ItemTapEvent = $m198.ItemTapEvent;
import * as $m199 from "../../src/extension/eui/events/PropertyEvent";
eui.PropertyEvent = $m199.PropertyEvent;
import * as $m200 from "../../src/extension/eui/events/ScrollerThrowEvent";
eui.ScrollerThrowEvent = $m200.ScrollerThrowEvent;
import * as $m201 from "../../src/extension/eui/events/UIEvent";
eui.UIEvent = $m201.UIEvent;
import * as $m202 from "../../src/extension/eui/exml/CodeFactory";
eui.CodeBase = $m202.CodeBase;
eui.EXClass = $m202.EXClass;
eui.EXCodeBlock = $m202.EXCodeBlock;
eui.EXFunction = $m202.EXFunction;
eui.EXVariable = $m202.EXVariable;
eui.EXState = $m202.EXState;
eui.EXAddItems = $m202.EXAddItems;
eui.EXSetProperty = $m202.EXSetProperty;
eui.EXSetStateProperty = $m202.EXSetStateProperty;
eui.EXBinding = $m202.EXBinding;
import * as $m203 from "../../src/extension/eui/exml/EXML";
eui.EXML = $m203.EXML;
eui.prefixURL = $m203.prefixURL;
eui.parse = $m203.parse;
eui.load = $m203.load;
eui.$loadAll = $m203.$loadAll;
eui.update = $m203.update;
eui.$parseURLContentAsJs = $m203.$parseURLContentAsJs;
eui.$parseURLContent = $m203.$parseURLContent;
import * as $m204 from "../../src/extension/eui/exml/EXMLParser";
eui.exmlConfig = $m204.exmlConfig;
eui.EXMLParser = $m204.EXMLParser;
import * as $m205 from "../../src/extension/eui/layouts/BasicLayout";
eui.measure = $m205.measure;
eui.updateDisplayList = $m205.updateDisplayList;
eui.BasicLayout = $m205.BasicLayout;
import * as $m206 from "../../src/extension/eui/layouts/HorizontalLayout";
eui.HorizontalLayout = $m206.HorizontalLayout;
import * as $m207 from "../../src/extension/eui/layouts/supportClasses/LayoutBase";
eui.LayoutBase = $m207.LayoutBase;
import * as $m208 from "../../src/extension/eui/layouts/supportClasses/LinearLayoutBase";
eui.LinearLayoutBase = $m208.LinearLayoutBase;
eui.ChildInfo = $m208.ChildInfo;
import * as $m209 from "../../src/extension/eui/layouts/TileLayout";
eui.TileLayout = $m209.TileLayout;
import * as $m210 from "../../src/extension/eui/layouts/VerticalLayout";
eui.VerticalLayout = $m210.VerticalLayout;
import * as $m211 from "../../src/extension/eui/states/AddItems";
eui.AddItems = $m211.AddItems;
eui.AddPosition = $m211.AddPosition;
import * as $m212 from "../../src/extension/eui/states/SetProperty";
eui.SetProperty = $m212.SetProperty;
import * as $m213 from "../../src/extension/eui/states/SetStateProperty";
eui.SetStateProperty = $m213.SetStateProperty;
import * as $m214 from "../../src/extension/eui/states/State";
eui.State = $m214.State;
eui.StateClient = $m214.StateClient;
eui.StateValues = $m214.StateValues;
import * as $m215 from "../../src/extension/eui/utils/MatrixUtil";
eui.MatrixUtil = $m215.MatrixUtil;
import * as $m216 from "../../src/extension/eui/utils/registerProperty";
eui.registerProperty = $m216.registerProperty;
import "../../src/egret/filters/BitmapFilterQuality";
import "../../src/egret/localStorage/web/WebLocalStorage";
import "../../src/egret/player/nodes/TextFormat";
import "../../src/egret/player/PlayerOption";
import "../../src/egret/player/Screen";
import "../../src/egret/text/ITextElement";
import "../../src/egret/i18n/en_US";
import "../../src/egret/i18n/zh_CN";
import "../../src/egret/utils/web/WebLogger";
import "../../src/egret/events/IEventDispatcher";
import "../../src/egret/media/SoundChannel";
import "../../src/egret/player/EgretEntry";
import "../../src/egret/text/web/WebTextMeasurer";
import "../../src/egret/web/EgretWeb";
import "../../src/egret/web/WebTexture";
import "../../src/extension/eui/core/IAssetAdapter";
import "../../src/extension/eui/core/IDisplayText";
import "../../src/extension/eui/core/IThemeAdapter";
import "../../src/extension/eui/i18n/en_US";
import "../../src/extension/eui/i18n/zh_CN";
import "../../src/extension/eui/collections/ICollection";
import "../../src/extension/eui/core/IItemRenderer";
import "../../src/extension/eui/core/IViewport";
import "../../src/extension/eui/states/IOverride";
