// Auto-generated ESM entry
import * as $m0 from "../../src/extension/game/display/FrameLabel";
egret.FrameLabel = $m0.FrameLabel;
import * as $m1 from "../../src/extension/game/display/MovieClipEvent";
egret.MovieClipEvent = $m1.MovieClipEvent;
import * as $m2 from "../../src/extension/game/display/ScrollTween";
egret.ScrollEase = $m2.ScrollEase;
egret.ScrollTween = $m2.ScrollTween;
import * as $m3 from "../../src/extension/game/net/URLLoaderDataFormat";
egret.URLLoaderDataFormat = $m3.URLLoaderDataFormat;
import * as $m4 from "../../src/extension/game/net/URLRequestHeader";
egret.URLRequestHeader = $m4.URLRequestHeader;
import * as $m5 from "../../src/extension/game/net/URLRequestMethod";
egret.URLRequestMethod = $m5.URLRequestMethod;
import * as $m6 from "../../src/extension/game/net/URLVariables";
egret.URLVariables = $m6.URLVariables;
import * as $m7 from "../../src/extension/game/player/Ticker";
egret.Ticker = $m7.Ticker;
import * as $m8 from "../../src/extension/game/utils/Recycler";
egret.Recycler = $m8.Recycler;
import * as $m9 from "../../src/extension/game/utils/setInterval";
egret.setInterval = $m9.setInterval;
egret.clearInterval = $m9.clearInterval;
import * as $m10 from "../../src/extension/game/utils/setTimeout";
egret.setTimeout = $m10.setTimeout;
egret.clearTimeout = $m10.clearTimeout;
import * as $m11 from "../../src/extension/game/display/MovieClipData";
egret.MovieClipData = $m11.MovieClipData;
import * as $m12 from "../../src/extension/game/display/ScrollViewProperties";
egret.ScrollViewProperties = $m12.ScrollViewProperties;
import * as $m13 from "../../src/extension/game/net/URLRequest";
egret.URLRequest = $m13.URLRequest;
import * as $m14 from "../../src/extension/game/system/MainContext";
egret.MainContext = $m14.MainContext;
import * as $m15 from "../../src/extension/game/display/MovieClip";
egret.MovieClip = $m15.MovieClip;
import * as $m16 from "../../src/extension/game/display/MovieClipDataFactory";
egret.MovieClipDataFactory = $m16.MovieClipDataFactory;
import * as $m17 from "../../src/extension/game/display/ScrollView";
egret.ScrollView = $m17.ScrollView;
import * as $m18 from "../../src/extension/game/net/URLLoader";
egret.URLLoader = $m18.URLLoader;
