// Auto-generated ESM entry
import "../../src/Defines.debug";
import * as $m0 from "../../src/egret/display/BitmapFillMode";
egret.BitmapFillMode = $m0.BitmapFillMode;
import * as $m1 from "../../src/egret/display/OrientationMode";
egret.OrientationMode = $m1.OrientationMode;
import * as $m2 from "../../src/egret/events/EventPhase";
egret.EventPhase = $m2.EventPhase;
import * as $m3 from "../../src/egret/i18n/tr";
egret.$locale_strings = $m3.$locale_strings;
egret.$language = $m3.$language;
egret.set = $m3.set;
egret.tr = $m3.tr;
import * as $m4 from "../../src/egret/localStorage/localStorage";
egret.getItem = $m4.getItem;
egret.setItem = $m4.setItem;
egret.removeItem = $m4.removeItem;
egret.clear = $m4.clear;
import * as $m5 from "../../src/egret/player/nodes/RenderNode";
egret.RenderNode = $m5.RenderNode;
egret.RenderNodeType = $m5.RenderNodeType;
import * as $m6 from "../../src/egret/player/paths/Path2D";
egret.Path2D = $m6.Path2D;
import * as $m7 from "../../src/egret/player/RenderBuffer";
egret.customHitTestBuffer = $m7.customHitTestBuffer;
egret.canvasHitTestBuffer = $m7.canvasHitTestBuffer;
egret.setCustomHitTestBuffer = $m7.setCustomHitTestBuffer;
egret.setCanvasHitTestBuffer = $m7.setCanvasHitTestBuffer;
egret.RenderBuffer = $m7.RenderBuffer;
egret.CanvasRenderBuffer = $m7.CanvasRenderBuffer;
import * as $m8 from "../../src/egret/player/StageScaleMode";
egret.StageScaleMode = $m8.StageScaleMode;
import * as $m9 from "../../src/egret/system/Capabilities";
egret.WEB = $m9.WEB;
egret.NATIVE = $m9.NATIVE;
egret.RUNTIME2 = $m9.RUNTIME2;
egret.MYGAME = $m9.MYGAME;
egret.WXGAME = $m9.WXGAME;
egret.BAIDUGAME = $m9.BAIDUGAME;
egret.QGAME = $m9.QGAME;
egret.OPPOGAME = $m9.OPPOGAME;
egret.QQGAME = $m9.QQGAME;
egret.VIVOGAME = $m9.VIVOGAME;
egret.QHGAME = $m9.QHGAME;
egret.TTGAME = $m9.TTGAME;
egret.FASTGAME = $m9.FASTGAME;
egret.TBCREATIVEAPP = $m9.TBCREATIVEAPP;
egret.Capabilities = $m9.Capabilities;
import * as $m10 from "../../src/egret/system/Console";
egret.assert = $m10.assert;
egret.setAssert = $m10.setAssert;
egret.warn = $m10.warn;
egret.error = $m10.error;
egret.log = $m10.log;
egret.setWarn = $m10.setWarn;
egret.setError = $m10.setError;
egret.setLog = $m10.setLog;
import * as $m11 from "../../src/egret/system/Implementation";
egret.registerImplementation = $m11.registerImplementation;
egret.getImplementation = $m11.getImplementation;
import * as $m12 from "../../src/egret/text/Font";
egret.fontResourceCache = $m12.fontResourceCache;
egret.setRegisterFontMapping = $m12.setRegisterFontMapping;
egret.registerFontMapping = $m12.registerFontMapping;
import * as $m13 from "../../src/egret/text/HorizontalAlign";
egret.HorizontalAlign = $m13.HorizontalAlign;
import * as $m14 from "../../src/egret/text/TextFieldInputType";
egret.TextFieldInputType = $m14.TextFieldInputType;
import * as $m15 from "../../src/egret/text/TextFieldType";
egret.TextFieldType = $m15.TextFieldType;
import * as $m16 from "../../src/egret/text/TextMeasurer";
egret.measureText = $m16.measureText;
import * as $m17 from "../../src/egret/utils/Base64Util";
egret.Base64Util = $m17.Base64Util;
import * as $m18 from "../../src/egret/utils/ByteArray";
egret.Endian = $m18.Endian;
egret.ByteArray = $m18.ByteArray;
import * as $m19 from "../../src/egret/utils/callLater";
egret.$callLaterFunctionList = $m19.$callLaterFunctionList;
egret.$callLaterThisList = $m19.$callLaterThisList;
egret.$callLaterArgsList = $m19.$callLaterArgsList;
egret.callLater = $m19.callLater;
egret.callAsyncState = $m19.callAsyncState;
egret.$callAsync = $m19.$callAsync;
import * as $m20 from "../../src/egret/utils/DataStructure";
egret.createMap = $m20.createMap;
import * as $m21 from "../../src/egret/utils/extends";
egret.superSetter = $m21.superSetter;
egret.superGetter = $m21.superGetter;
import * as $m22 from "../../src/egret/utils/getDefinitionByName";
egret.getDefinitionByName = $m22.getDefinitionByName;
import * as $m23 from "../../src/egret/utils/getOption";
egret.getOption = $m23.getOption;
import * as $m24 from "../../src/egret/utils/getQualifiedClassName";
egret.getQualifiedClassName = $m24.getQualifiedClassName;
import * as $m25 from "../../src/egret/utils/getQualifiedSuperclassName";
egret.getQualifiedSuperclassName = $m25.getQualifiedSuperclassName;
import * as $m26 from "../../src/egret/utils/HashObject";
egret.$hashCount = $m26.$hashCount;
egret.HashObject = $m26.HashObject;
import * as $m27 from "../../src/egret/utils/Logger";
egret.Logger = $m27.Logger;
import * as $m28 from "../../src/egret/utils/NumberUtils";
egret.NumberUtils = $m28.NumberUtils;
import * as $m29 from "../../src/egret/utils/toColorString";
egret.toColorString = $m29.toColorString;
import * as $m30 from "../../src/egret/utils/XML";
egret.XML = $m30.XML;
import * as $m31 from "../../src/egret/web/rendering/webgl/shaders/EgretShaderLib";
egret.EgretShaderLib = $m31.EgretShaderLib;
import * as $m32 from "../../src/egret/web/rendering/webgl/WebGLUtils";
egret.WebGLUtils = $m32.WebGLUtils;
import * as $m33 from "../../src/egret/web/WebGetOption";
import * as $m34 from "../../src/egret/web/WebHideHandler";
egret.WebLifeCycleHandler = $m34.WebLifeCycleHandler;
import * as $m35 from "../../src/egret/web/WebXML";
egret.XMLNode = $m35.XMLNode;
egret.XMLText = $m35.XMLText;
import * as $m36 from "../../src/egret/player/nodes/TextNode";
egret.TextNode = $m36.TextNode;
import * as $m37 from "../../src/egret/player/paths/FillPath";
egret.FillPath = $m37.FillPath;
import * as $m38 from "../../src/egret/player/paths/StrokePath";
egret.StrokePath = $m38.StrokePath;
import * as $m39 from "../../src/egret/web/WebCapability";
egret.WebCapability = $m39.WebCapability;
import * as $m40 from "../../src/egret/geom/Point";
egret.$TempPoint = $m40.$TempPoint;
egret.Point = $m40.Point;
import * as $m41 from "../../src/egret/player/ScreenAdapter";
egret.screenAdapter = $m41.screenAdapter;
egret.setScreenAdapter = $m41.setScreenAdapter;
egret.DefaultScreenAdapter = $m41.DefaultScreenAdapter;
import * as $m42 from "../../src/egret/web/rendering/webgl/TextAtlasStrategy";
egret.TextBlock = $m42.TextBlock;
egret.Line = $m42.Line;
egret.Page = $m42.Page;
egret.Book = $m42.Book;
import * as $m43 from "../../src/egret/web/rendering/webgl/WebGLRenderTarget";
egret.WebGLRenderTarget = $m43.WebGLRenderTarget;
import * as $m44 from "../../src/egret/geom/Rectangle";
egret.$TempRectangle = $m44.$TempRectangle;
egret.Rectangle = $m44.Rectangle;
import * as $m45 from "../../src/egret/geom/Matrix";
egret.$TempMatrix = $m45.$TempMatrix;
egret.Matrix = $m45.Matrix;
import * as $m46 from "../../src/egret/player/nodes/GroupNode";
egret.GroupNode = $m46.GroupNode;
import * as $m47 from "../../src/egret/player/paths/GradientFillPath";
egret.GradientFillPath = $m47.GradientFillPath;
import * as $m48 from "../../src/egret/player/nodes/GraphicsNode";
egret.GraphicsNode = $m48.GraphicsNode;
import * as $m49 from "../../src/egret/3d/EgretPro";
egret.egret2dDriveMode = $m49.egret2dDriveMode;
egret.mainCanvas = $m49.mainCanvas;
egret.createTextureFrom3dScene = $m49.createTextureFrom3dScene;
egret.createTextureForCameras = $m49.createTextureForCameras;
egret.execute = $m49.execute;
egret.register = $m49.register;
egret.addEventListener = $m49.addEventListener;
egret.removeEventListener = $m49.removeEventListener;
egret.dispatch = $m49.dispatch;
import * as $m50 from "../../src/egret/display/Bitmap";
egret.Bitmap = $m50.Bitmap;
import * as $m51 from "../../src/egret/display/BitmapData";
egret.etc_alpha_mask = $m51.etc_alpha_mask;
egret.engine_default_empty_texture = $m51.engine_default_empty_texture;
egret.is_compressed_texture = $m51.is_compressed_texture;
egret.glContext = $m51.glContext;
egret.UNPACK_PREMULTIPLY_ALPHA_WEBGL = $m51.UNPACK_PREMULTIPLY_ALPHA_WEBGL;
egret.CompressedTextureData = $m51.CompressedTextureData;
egret.BitmapData = $m51.BitmapData;
import * as $m52 from "../../src/egret/display/BlendMode";
egret.blendModeToNumber = $m52.blendModeToNumber;
egret.numberToBlendMode = $m52.numberToBlendMode;
egret.BlendMode = $m52.BlendMode;
import * as $m53 from "../../src/egret/display/CapsStyle";
egret.CapsStyle = $m53.CapsStyle;
import * as $m54 from "../../src/egret/display/DisplayObject";
egret.DisplayObject = $m54.DisplayObject;
import * as $m55 from "../../src/egret/display/DisplayObjectContainer";
egret.DisplayObjectContainer = $m55.DisplayObjectContainer;
import * as $m56 from "../../src/egret/display/GradientType";
egret.GradientType = $m56.GradientType;
import * as $m57 from "../../src/egret/display/Graphics";
egret.Graphics = $m57.Graphics;
import * as $m58 from "../../src/egret/display/JointStyle";
egret.JointStyle = $m58.JointStyle;
import * as $m59 from "../../src/egret/display/KTXContainer";
egret.KTXContainer = $m59.KTXContainer;
import * as $m60 from "../../src/egret/display/Mesh";
egret.Mesh = $m60.Mesh;
import * as $m61 from "../../src/egret/display/RenderTexture";
egret.RenderTexture = $m61.RenderTexture;
import * as $m62 from "../../src/egret/display/Shape";
egret.Shape = $m62.Shape;
import * as $m63 from "../../src/egret/display/Sprite";
egret.Sprite = $m63.Sprite;
import * as $m64 from "../../src/egret/display/SpriteSheet";
egret.SpriteSheet = $m64.SpriteSheet;
import * as $m65 from "../../src/egret/display/Stage";
egret.Stage = $m65.Stage;
import * as $m66 from "../../src/egret/display/Texture";
egret.$TextureScaleFactor = $m66.$TextureScaleFactor;
egret.Texture = $m66.Texture;
import * as $m67 from "../../src/egret/events/Event";
egret.Event = $m67.Event;
import * as $m68 from "../../src/egret/events/EventDispatcher";
egret.EventDispatcher = $m68.EventDispatcher;
import * as $m69 from "../../src/egret/events/FocusEvent";
egret.FocusEvent = $m69.FocusEvent;
import * as $m70 from "../../src/egret/events/GeolocationEvent";
egret.GeolocationEvent = $m70.GeolocationEvent;
import * as $m71 from "../../src/egret/events/HTTPStatusEvent";
egret.HTTPStatusEvent = $m71.HTTPStatusEvent;
import * as $m72 from "../../src/egret/events/IOErrorEvent";
egret.IOErrorEvent = $m72.IOErrorEvent;
import * as $m73 from "../../src/egret/events/MotionEvent";
egret.MotionEvent = $m73.MotionEvent;
import * as $m74 from "../../src/egret/events/OrientationEvent";
egret.OrientationEvent = $m74.OrientationEvent;
import * as $m75 from "../../src/egret/events/ProgressEvent";
egret.ProgressEvent = $m75.ProgressEvent;
import * as $m76 from "../../src/egret/events/StageOrientationEvent";
egret.StageOrientationEvent = $m76.StageOrientationEvent;
import * as $m77 from "../../src/egret/events/TextEvent";
egret.TextEvent = $m77.TextEvent;
import * as $m78 from "../../src/egret/events/TimerEvent";
egret.TimerEvent = $m78.TimerEvent;
import * as $m79 from "../../src/egret/events/TouchEvent";
egret.TouchEvent = $m79.TouchEvent;
import * as $m80 from "../../src/egret/filters/BlurFilter";
egret.BlurFilter = $m80.BlurFilter;
import * as $m81 from "../../src/egret/filters/ColorMatrixFilter";
egret.ColorMatrixFilter = $m81.ColorMatrixFilter;
import * as $m82 from "../../src/egret/filters/CustomFilter";
egret.CustomFilter = $m82.CustomFilter;
import * as $m83 from "../../src/egret/filters/DropShadowFilter";
egret.DropShadowFilter = $m83.DropShadowFilter;
import * as $m84 from "../../src/egret/filters/Filter";
egret.Filter = $m84.Filter;
import * as $m85 from "../../src/egret/filters/GlowFilter";
egret.GlowFilter = $m85.GlowFilter;
import * as $m86 from "../../src/egret/media/Sound";
egret.usingChannel = $m86.usingChannel;
egret.$pushSoundChannel = $m86.$pushSoundChannel;
egret.$popSoundChannel = $m86.$popSoundChannel;
egret.setSound = $m86.setSound;
egret.Sound = $m86.Sound;
import * as $m87 from "../../src/egret/media/Video";
egret.Video = $m87.Video;
egret.setVideo = $m87.setVideo;
import * as $m88 from "../../src/egret/media/web/HtmlSound";
egret.HtmlSound = $m88.HtmlSound;
import * as $m89 from "../../src/egret/media/web/HtmlSoundChannel";
egret.HtmlSoundChannel = $m89.HtmlSoundChannel;
import * as $m90 from "../../src/egret/media/web/WebAudioSound";
egret.WebAudioDecode = $m90.WebAudioDecode;
egret.WebAudioSound = $m90.WebAudioSound;
import * as $m91 from "../../src/egret/media/web/WebAudioSoundChannel";
egret.WebAudioSoundChannel = $m91.WebAudioSoundChannel;
import * as $m92 from "../../src/egret/media/web/WebVideo";
egret.WebVideo = $m92.WebVideo;
import * as $m93 from "../../src/egret/net/HttpMethod";
egret.GET = $m93.GET;
egret.POST = $m93.POST;
import * as $m94 from "../../src/egret/net/HttpRequest";
egret.setHttpRequest = $m94.setHttpRequest;
egret.HttpRequest = $m94.HttpRequest;
import * as $m95 from "../../src/egret/net/HttpResponseType";
egret.HttpResponseType = $m95.HttpResponseType;
import * as $m96 from "../../src/egret/net/ImageLoader";
egret.setImageLoader = $m96.setImageLoader;
egret.ImageLoader = $m96.ImageLoader;
import * as $m97 from "../../src/egret/net/web/WebHttpRequest";
egret.WebHttpRequest = $m97.WebHttpRequest;
import * as $m98 from "../../src/egret/net/web/WebImageLoader";
egret.WebImageLoader = $m98.WebImageLoader;
import * as $m99 from "../../src/egret/player/DisplayList";
egret.DisplayList = $m99.DisplayList;
import * as $m100 from "../../src/egret/player/FPSDisplay";
egret.setFPSDisplay = $m100.setFPSDisplay;
egret.FPSDisplay = $m100.FPSDisplay;
import * as $m101 from "../../src/egret/player/nodes/BitmapNode";
egret.BitmapNode = $m101.BitmapNode;
import * as $m102 from "../../src/egret/player/nodes/MeshNode";
egret.MeshNode = $m102.MeshNode;
import * as $m103 from "../../src/egret/player/nodes/NormalBitmapNode";
egret.NormalBitmapNode = $m103.NormalBitmapNode;
import * as $m104 from "../../src/egret/player/Player";
egret.$TempStage = $m104.$TempStage;
egret.$logToFPS = $m104.$logToFPS;
egret.$warnToFPS = $m104.$warnToFPS;
egret.$errorToFPS = $m104.$errorToFPS;
egret.setRenderMode = $m104.setRenderMode;
egret.setWebGLRenderContext = $m104.setWebGLRenderContext;
egret.WebGLRenderContext = $m104.WebGLRenderContext;
egret.nativeRender = $m104.nativeRender;
egret.Player = $m104.Player;
import * as $m105 from "../../src/egret/player/rendering/CanvasRenderer";
egret.getFontString = $m105.getFontString;
egret.getRGBAString = $m105.getRGBAString;
egret.CanvasRenderer = $m105.CanvasRenderer;
import * as $m106 from "../../src/egret/player/SystemRenderer";
egret.systemRenderer = $m106.systemRenderer;
egret.canvasRenderer = $m106.canvasRenderer;
egret.setSystemRenderer = $m106.setSystemRenderer;
egret.setCanvasRenderer = $m106.setCanvasRenderer;
egret.createCanvas = $m106.createCanvas;
egret.resizeContext = $m106.resizeContext;
egret.getContextWebGL = $m106.getContextWebGL;
egret.getContext2d = $m106.getContext2d;
egret.createTexture = $m106.createTexture;
egret._createTexture = $m106._createTexture;
egret.drawTextureElements = $m106.drawTextureElements;
egret.measureTextWith = $m106.measureTextWith;
egret.createCanvasRenderBufferSurface = $m106.createCanvasRenderBufferSurface;
egret.resizeCanvasRenderBuffer = $m106.resizeCanvasRenderBuffer;
import * as $m107 from "../../src/egret/player/SystemTicker";
egret.$START_TIME = $m107.$START_TIME;
egret.$invalidateRenderFlag = $m107.$invalidateRenderFlag;
egret.invalidateRenderFlag = $m107.invalidateRenderFlag;
egret.$requestRenderingFlag = $m107.$requestRenderingFlag;
egret.stage = $m107.stage;
egret.contexts = $m107.contexts;
egret.onResume = $m107.onResume;
egret.onPause = $m107.onPause;
egret.addLifecycleListener = $m107.addLifecycleListener;
egret.ticker = $m107.ticker;
egret.SystemTicker = $m107.SystemTicker;
egret.LifecycleContext = $m107.LifecycleContext;
import * as $m108 from "../../src/egret/player/TouchHandler";
egret.TouchHandler = $m108.TouchHandler;
import * as $m109 from "../../src/egret/sensor/DeviceOrientation";
egret.DeviceOrientation = $m109.DeviceOrientation;
egret.setDeviceOrientation = $m109.setDeviceOrientation;
import * as $m110 from "../../src/egret/sensor/Geolocation";
egret.setGeolocation = $m110.setGeolocation;
egret.Geolocation = $m110.Geolocation;
import * as $m111 from "../../src/egret/sensor/Motion";
egret.setMotion = $m111.setMotion;
egret.Motion = $m111.Motion;
import * as $m112 from "../../src/egret/sensor/web/WebDeviceOrientation";
egret.WebDeviceOrientation = $m112.WebDeviceOrientation;
import * as $m113 from "../../src/egret/sensor/web/WebGeolocation";
egret.WebGeolocation = $m113.WebGeolocation;
import * as $m114 from "../../src/egret/sensor/web/WebMotion";
egret.WebMotion = $m114.WebMotion;
import * as $m115 from "../../src/egret/text/BitmapFont";
egret.BitmapFont = $m115.BitmapFont;
import * as $m116 from "../../src/egret/text/BitmapText";
egret.BitmapText = $m116.BitmapText;
import * as $m117 from "../../src/egret/text/HtmlTextParser";
egret.HtmlTextParser = $m117.HtmlTextParser;
import * as $m118 from "../../src/egret/text/InputController";
egret.InputController = $m118.InputController;
import * as $m119 from "../../src/egret/text/StageText";
egret.StageText = $m119.StageText;
egret.setStageText = $m119.setStageText;
import * as $m120 from "../../src/egret/text/TextField";
egret.addLanguageWordWrapRegex = $m120.addLanguageWordWrapRegex;
egret.getAllSupportLanguageWordWrap = $m120.getAllSupportLanguageWordWrap;
egret.getUsingWordWrap = $m120.getUsingWordWrap;
egret.cancelLanguageWordWrapRegex = $m120.cancelLanguageWordWrapRegex;
egret.TextField = $m120.TextField;
import * as $m121 from "../../src/egret/text/TextFieldUtils";
egret.TextFieldUtils = $m121.TextFieldUtils;
import * as $m122 from "../../src/egret/text/VerticalAlign";
egret.VerticalAlign = $m122.VerticalAlign;
import * as $m123 from "../../src/egret/text/web/HTML5StageText";
egret.$getTextAdapter = $m123.$getTextAdapter;
egret.$cacheTextAdapter = $m123.$cacheTextAdapter;
egret.HTML5StageText = $m123.HTML5StageText;
egret.HTMLInput = $m123.HTMLInput;
import * as $m124 from "../../src/egret/utils/getTimer";
egret.getTimer = $m124.getTimer;
import * as $m125 from "../../src/egret/utils/hasDefinition";
egret.hasDefinition = $m125.hasDefinition;
import * as $m126 from "../../src/egret/utils/is";
egret.is = $m126.is;
import * as $m127 from "../../src/egret/utils/registerClass";
egret.registerClass = $m127.registerClass;
import * as $m128 from "../../src/egret/utils/startTick";
egret.startTick = $m128.startTick;
import * as $m129 from "../../src/egret/utils/stopTick";
egret.stopTick = $m129.stopTick;
import * as $m130 from "../../src/egret/utils/Timer";
egret.Timer = $m130.Timer;
import * as $m131 from "../../src/egret/web/Html5Capatibility";
egret.getPrefixStyleName = $m131.getPrefixStyleName;
egret.getPrefix = $m131.getPrefix;
egret.AudioType = $m131.AudioType;
egret.Html5Capatibility = $m131.Html5Capatibility;
import * as $m132 from "../../src/egret/web/rendering/CanvasRenderBuffer";
import * as $m133 from "../../src/egret/web/rendering/webgl/EgretWebGLAttribute";
egret.EgretWebGLAttribute = $m133.EgretWebGLAttribute;
import * as $m134 from "../../src/egret/web/rendering/webgl/EgretWebGLProgram";
egret.EgretWebGLProgram = $m134.EgretWebGLProgram;
import * as $m135 from "../../src/egret/web/rendering/webgl/EgretWebGLUniform";
egret.EgretWebGLUniform = $m135.EgretWebGLUniform;
import * as $m136 from "../../src/egret/web/rendering/webgl/TextAtlasRender";
egret.textAtlasRenderEnable = $m136.textAtlasRenderEnable;
egret.__textAtlasRender__ = $m136.__textAtlasRender__;
egret.property_drawLabel = $m136.property_drawLabel;
egret.DrawLabel = $m136.DrawLabel;
egret.TextAtlasRender = $m136.TextAtlasRender;
import * as $m137 from "../../src/egret/web/rendering/webgl/WebGLDrawCmdManager";
egret.WebGLDrawCmdManager = $m137.WebGLDrawCmdManager;
import * as $m138 from "../../src/egret/web/rendering/webgl/WebGLRenderBuffer";
egret.renderBufferPool = $m138.renderBufferPool;
egret.WebGLRenderBuffer = $m138.WebGLRenderBuffer;
import * as $m139 from "../../src/egret/web/rendering/webgl/WebGLRenderContext";
import * as $m140 from "../../src/egret/web/rendering/webgl/WebGLRenderer";
egret.WebGLRenderer = $m140.WebGLRenderer;
import * as $m141 from "../../src/egret/web/rendering/webgl/WebGLVertexArrayObject";
egret.isIOS14Device = $m141.isIOS14Device;
egret.setIsIOS14Device = $m141.setIsIOS14Device;
egret.WebGLVertexArrayObject = $m141.WebGLVertexArrayObject;
import * as $m142 from "../../src/egret/web/WebFps";
egret.WebFps = $m142.WebFps;
import * as $m143 from "../../src/egret/web/WebPlayer";
egret.WebPlayer = $m143.WebPlayer;
import * as $m144 from "../../src/egret/web/WebSysImpl";
import * as $m145 from "../../src/egret/web/WebTouchHandler";
egret.WebTouchHandler = $m145.WebTouchHandler;
import "../../src/egret/filters/BitmapFilterQuality";
import "../../src/egret/localStorage/web/WebLocalStorage";
import "../../src/egret/player/nodes/TextFormat";
import "../../src/egret/player/PlayerOption";
import "../../src/egret/player/Screen";
import "../../src/egret/text/ITextElement";
import "../../src/egret/i18n/en_US";
import "../../src/egret/i18n/zh_CN";
import "../../src/egret/utils/web/WebLogger";
import "../../src/egret/events/IEventDispatcher";
import "../../src/egret/media/SoundChannel";
import "../../src/egret/player/EgretEntry";
import "../../src/egret/text/web/WebTextMeasurer";
import "../../src/egret/web/EgretWeb";
import "../../src/egret/web/WebTexture";
