import esbuild from "esbuild";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const distDir = path.join(__dirname, "dist");

fs.mkdirSync(distDir, { recursive: true });
fs.copyFileSync(path.join(__dirname, "game.json"), path.join(distDir, "game.json"));

await esbuild.build({
  entryPoints: [path.join(__dirname, "src/game.ts")],
  bundle: true,
  outfile: path.join(distDir, "game.js"),
  format: "iife",
  platform: "neutral",
  target: "es2020",
  minify: false,
  // WeChat Mini Game globals
  define: {
    "globalThis.gameCanvas": "undefined",
  },
  // Strip browser-specific code via dead-code elimination hints
  // The engine's WebAdapter is tree-shaken when DOM APIs are undefined
  banner: {
    js: `// Egret Engine R - WeChat Mini Game
// Generated by esbuild. Do not edit.
`,
  },
});

console.log("✅ Built: dist/game.js");
console.log("📱 Open with WeChat DevTools → Import project → Select examples/wx-game/dist/");
